### ISSUE TITLE
Error: Offset is out of bounds

### ISSUE THREAD

**Issue by ursulashan** [schmuli/atom-less#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.12
**Thrown From**: [atom-less](https://github.com/schmuli/atom-less) package, v0.1.10
### Stack Trace

Uncaught Error: Offset is out of bounds

```
At fs.js:582

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at FirstLine.readFile (/Users/shanrj/.atom/packages/atom-less/lib/firstline.coffee:27:12)
    at FirstLine.startReading (/Users/shanrj/.atom/packages/atom-less/lib/firstline.coffee:23:10)
    at /Users/shanrj/.atom/packages/atom-less/lib/firstline.coffee:14:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -8:59.9.0 git-plus:commit (atom-text-editor.editor.is-focused)
     -8:51.6.0 core:undo (atom-text-editor.editor.is-focused)
     -8:46.7.0 css-comb:comb (atom-text-editor.editor.is-focused)
     -8:41.7.0 core:save (atom-text-editor.editor.is-focused)
     -8:00.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -7:59.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -7:59.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:57.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -7:56.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
 16x -7:53.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:40.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:40.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:05.8.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
     -5:44.8.0 core:save (div.package-detail.panels-item)
     -0:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "wrap-guide",
      "atom-beautify"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".DS_Store",
      "Thumbs.db"
    ],
    "packagesWithKeymapsDisabled": [
      "markdown-preview"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-css-comb, v3.1.0
atom-less, v0.1.10
atom-minify, v0.7.5
emmet, v2.4.3
file-icons, v1.7.21
git-plus, v5.18.0
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
markdown-preview-enhanced, v0.8.7
markdown-preview-plus, v2.4.0
php-cs-fixer, v2.5.9
react, v0.16.0
react-snippets, v0.5.0

# Dev
No dev packages
```

**Comment by schmuli** [comment]
@ursulashan I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
