### ISSUE TITLE
Uncaught Error: Notification must be created with string message: Error: EBUSY: resource busy or ...

### ISSUE THREAD

**Issue by Vladislav-vlk** [schmuli/atom-less#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-less](https://github.com/schmuli/atom-less) package 0.1.10

### Stack Trace

Uncaught Error: Notification must be created with string message: Error: EBUSY: resource busy or locked, open 'C:\Users\Владислав\OneDrive\ПРОЕКТЫ\тест2\css\style.css'

```
At C:\Users\Владислав\AppData\Local\atom\app-1.21.2\resources\app\src\notification.js:25

Error: Notification must be created with string message: Error: EBUSY: resource busy or locked, open 'C:\Users\Владислав\OneDrive\ПРОЕКТЫ\тест2\css\style.css'
    at Notification.module.exports.Notification.validate (~/AppData/Local/atom/app-1.21.2/resources/app/src/notification.js:25:21)
    at new Notification (~/AppData/Local/atom/app-1.21.2/resources/app/src/notification.js:20:18)
    at NotificationManager.module.exports.NotificationManager.addError (~/AppData/Local/atom/app-1.21.2/resources/app/src/notification-manager.js:41:41)
    at /packages/atom-less/lib/output-writer.coffee:20:40
    at /packages/atom-less/node_modules/async/lib/async.js:726:13
    at /packages/atom-less/node_modules/async/lib/async.js:52:16
    at /packages/atom-less/node_modules/async/lib/async.js:264:21
    at /packages/atom-less/node_modules/async/lib/async.js:44:16
    at /packages/atom-less/node_modules/async/lib/async.js:723:17
    at /packages/atom-less/node_modules/async/lib/async.js:167:37
    at fs.js:1213:7
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -2:19.4.0 core:paste (input.hidden-input)
 19x -2:18.8.0 core:save (input.hidden-input)
  2x -1:41.8.0 core:backspace (input.hidden-input)
     -1:40.7.0 editor:newline (input.hidden-input)
     -1:39.6.0 core:save (input.hidden-input)
     -0:55.1.0 core:cut (input.hidden-input)
     -0:54.9.0 core:backspace (input.hidden-input)
     -0:53.3.0 core:undo (input.hidden-input)
     -0:47.7.0 core:cut (input.hidden-input)
  4x -0:47.4.0 core:backspace (input.hidden-input)
     -0:46.3.0 core:save (input.hidden-input)
     -0:39.7.0 editor:newline (input.hidden-input)
     -0:39.5.0 core:paste (input.hidden-input)
     -0:39 core:save (input.hidden-input)
  2x -0:30.1.0 core:undo (input.hidden-input)
 14x -0:29.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-less 0.1.10 
emmet 2.4.3 
file-icons 2.1.13 
git-control 0.9.0 
```

**Comment by schmuli** [comment]
@Vladislav-vlk I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
