### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadFile' of undefined

### ISSUE THREAD

**Issue by babbla** [schmuli/atom-less#6]
Hello! I have this error on all my computers. (Windows 7, Windows 10 and Ubuntu)

```
TypeError: Cannot read property 'uploadFile' of undefined
    at handleEvent (file:///C:/Users/Usuario/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (file:///C:/Users/Usuario/.atom/packages/remote-sync/index.coffee:95:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Usuario\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Usuario\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Usuario\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Usuario\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\Usuario\AppData\Local\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

**Comment by schmuli** [comment]
According to the stack-trace, this error happened in the `remote-sync` package, and not in `atom-less`.

Can you please check if this is related somehow to yongkangchen/remote-sync#147?

**Comment by schmuli** [comment]
I'm closing this since I haven't heard any more on this issue.
